version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    restart: unless-stopped
    build:
      context: ./src
    volumes:
      - static:/app/static
      - media:/app/media
      - ./src:/app
    entrypoint: /app/wsgi-entrypoint.sh
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - 8000

  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - .env
    depends_on:
      - db
      - backend

volumes:
  static:
  postgres_data:
  media:
